name: Build nightly

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Compile ROM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Make application
        run: |
          chmod -R 755 buildtools/
          make 3dsx cia
      - name: Prepare for build publishing
        run: |
          mkdir -p out/3dsx/rom
          mkdir -p out/cia/rom
          cp output/GeometryDash3DS.3dsx out/3dsx/rom
          cp output/GeometryDash3DS.cia out/cia/rom
      - name: Publish 3dsx to GH Actions
        uses: actions/upload-artifact@main
        with:
          name: gd3ds-3dsx
          path: out/3dsx/rom
      - name: Publish cia to GH Actions
        uses: actions/upload-artifact@main
        with:
          name: gd3ds-cia
          path: out/cia/rom
            
